/**
 Start of Avision Standard Header
 Copyright (c) 2007-2008 Avision INC.
     
 All rights reserved.  Proprietary and confidential.
 	
 Header file contains error constant for Avision's API
 
 Designer: Hairay
 Creation Date: 2006/04/10
   	 
*/

#ifndef __ERROR_DEF__
#define __ERROR_DEF__

// OS 使用錯誤代碼(0, 1- 255 in tx_api.h) 

//共用錯誤代碼(0, 2500-2549)
#define API_SUCCESS			0
#define API_OK              API_SUCCESS

//使用在系統的記憶體的配置,(ex:call malloc 得到null pointer)
#define API_MEM_EMPTY			2500
//使用在物件內部的記憶體配置
#define API_BUFFER_EMPTY        2501
//未按照 call sequence 使用
#define API_WRONG_FLOW			2502
//job的處理階段是在中斷情形
#define API_ABORTED				2503
//等待時間超過預設值(非device)
#define API_TIME_OUT			2504
//等待時間超過預設值(device)
#define API_GET_DEVICE_TIMEOUT	2505
//已經有AP在使用這個device
#define API_DEVICE_BUSY			2506
//已經有AP在使用這個物件
#define API_JOB_APP_BUSY		2507
//傳入不正確的參數
#define API_WRONG_PARAMETER		2508
//Device 提早回應結束
#define API_DEVICE_STOP			2509
//Scan&Print Init fail造成 MFP Error
#define API_DEVICE_INIT_FAIL	2510

#define API_PTR_ERROR           2511

//無法確定的原因,希望盡量不要使用這個錯誤代碼
#define API_UNKNOW_ERROR        2549
#define API_FAIL                API_UNKNOW_ERROR

// 共用register access(2550-2559)
#define API_REG_OK              0       /* register access successful       */
#define API_REG_FAIL            2550    /* unspecified failure              */
#define API_REG_NI              2551    /* register access not initialized  */
#define API_REG_WO              2552    /* register is write-only           */
#define API_REG_RO              2553    /* register is read-only            */

// nvram(2560-2569)
#define API_NVRAM_WRONG_ADDR	2560
#define API_NVRAM_WRITE_FAIL1	2561
#define API_NVRAM_WRITE_FAIL2	2562
#define API_NVRAM_WRITE_FAIL3	2563
#define API_NVRAM_READ_FAIL1	2564
#define API_NVRAM_READ_FAIL2	2565
#define API_NVRAM_READ_FAIL3	2566
#define API_NVRAM_RW_TEST_FAIL	2567


// usb(2570-2579)
#define API_USB_DISCONNECT		2570
// 無法傳送packet
#define API_USB_BUSY			2571

//FlexRisc(2580-2589)
#define API_FRIF_RESP_FAIL		2580


//From ParseScanCmdUCO.h   It take with the errorDef.h
//Scanner Old Error Code 2000 -> 2099
//Scanner New Error Code 3000 -> 3099
#define AJAX_SUCCESS 					0
#define AJAX_SCANNER_READY             0

#define AJAX_DRIVER_BUSY				2000
#define AJAX_SCANNER_BUSY				2001
#define AJAX_PORT_BUSY					2002
#define AJAX_HANDSHAKE_TIMEOUT			2003
#define AJAX_SCANNER_CONNECT_FAILED		2004
#define AJAX_INVALID_PARAMETER			2005
#define AJAX_ALLOCATE_MEMORY_FAILED		2006
#define AJAX_LAMP_BROKEN				2007
#define AJAX_LOCK_ERROR					2008

#define AJAX_READ_CANCEL				2010
#define AJAX_REGISTER_RW_FAILED			2011
#define AJAX_MEMORY_RW_FAILED			2012
#define AJAX_PAPER_JAM					2013
#define AJAX_ADF_COVER_OPEN				2014
#define AJAX_NO_PAPER_IN_ADF			2015	
#define AJAX_NOT_FOUND_XPA_KIT			2016
//#define AJAX_NOT_FOUND_XPA_KIT			2017
#define AJAX_XPA_KIT_POWER_OFF			2018
#define AJAX_NOT_FOUNT_WINASPI			2019
#define AJAX_CALIBRATION_ERROR			2020
#define AJAX_HOME_SENSOR_ERROR			2021

#define AJAX_SYSTEM_ERROR				2023
#define AJAX_WRITE_NVM_ERROR			2024
#define AJAX_PAPER_IN_MULTI_TRAY		2025
#define AJAX_FRONT_DOOR_OPEN			2026
#define AJAX_PARAMETER_NOT_SUPPORT		2027

#define AJAX_UNKNOW_ERROR				2999

#define AJAX_FB_HOME_SENSOR_ERR			3001
#define AJAX_ADF_HOME_SENSOR_ERR		3002
#define AJAX_FB_DRAM_ERR				3003
#define AJAX_ADF_DRAM_ERR				3004
#define AJAX_FB_LAMP_ERR				3005
#define AJAX_ADF_LAMP_ERR				3006
#define AJAX_FB_COVER_OPEN				3007
#define AJAX_ACCESSARIES_UNPLUGGED		3008
#define AJAX_PREFEEDING					3009
#define AJAX_FB_MOTOR_ERR        3010
#define AJAX_ADF_MOTOR_ERR       3011
#define AJAX_SCAN_END		     3012
#define AJAX_BLANK_PAGE_DETECT		    3013


#define AJAX_PARAMETER_CHECK_ERROR		1
#define AJAX_MULTI_FEED 				2
#define AJAX_END_OF_PAGE				3
#define AJAX_SCANNER_WARM_UP			4
#define AJAX_SCANNER_IF_ERROR           AJAX_PAPER_JAM



#define SCANNER_ERROR_BASE	3100

//Start of O_ScInterface error code
#define SC_INTERFACE_ERROR_BASE	(SCANNER_ERROR_BASE + 300)
#define SC_INTERFACE_TMP_BUFFER_FULL		(SC_INTERFACE_ERROR_BASE + 1)
#define SC_INTERFACE_CANT_ALLOCATE_BUFFER	(SC_INTERFACE_ERROR_BASE + 2)
#define SC_INTERFACE_BUFFER_FUNC_POINT_NULL (SC_INTERFACE_ERROR_BASE + 3)
#define SC_INTERFACE_LINE_SIZE_SETUP_ERROR	(SC_INTERFACE_ERROR_BASE + 3)
//end of O_ScInterface error code


//	scanner FlexRISC error code
#define SC_FRISC_ERROR_BASE		(SCANNER_ERROR_BASE+400)
#define SC_FRISC_MODE_ERROR		(SC_FRISC_ERROR_BASE + 1)


//Print error code
#define PRINTER_ERROR_BASE         4000					//定義Printer Engine error 的Base。(此定義並需定義在ErrorDef.h之內)
#define	API_ENG_CONNECT_ERROR      (PRINTER_ERROR_BASE + 1)	//定義Printer Engine無法Ready或者Printer Engine未接的Error code，此定義並需定義在ErrorDef.h之內。(Printer 的error code定義在PRINTER_ERROR_BASE之後)
#define API_ENG_CMD_NAK            (PRINTER_ERROR_BASE + 2)	//定義Printer Engine收到NAK的error code(此定義並需定義在ErrorDef.h之內)
#define ENG_NON_AVAILABLE          (PRINTER_ERROR_BASE + 3)    // AP request, but engine not ready
#define ENG_FW_SUSPEND_ERROR       (PRINTER_ERROR_BASE + 4)
//#define PRINTER_NULL_POINTER       (PRINTER_ERROR_BASE + 5)    // null pointer error
//#define PRINTER_QUEUE_FULL         (PRINTER_ERROR_BASE + 6)    // queue full
//#define PRINTER_QUEUE_EMPTY        (PRINTER_ERROR_BASE + 7)    // queue empty
//#define PRINTER_ARRAY_FULL         (PRINTER_ERROR_BASE + 8)    // array full

#define PRINTER_MEM_ALLOC_NULL_POINTER            (PRINTER_ERROR_BASE + 5)    // mem allocate memory null pointer error
#define PRINTER_MEM_ALLOC_ALIGN_ZERO              (PRINTER_ERROR_BASE + 6)

#define PRINTER_MEM_FREE_NULL_POINTER             (PRINTER_ERROR_BASE + 7)    // mem free memory null pointer error
#define PRINTER_MEM_FREE_PAD_ZERO                 (PRINTER_ERROR_BASE + 8)


#define PRINTER_PARAM_NEW_NULL_HANDLE             (PRINTER_ERROR_BASE + 10)
#define PRINTER_PARAM_NEW_NULL_POINTER            (PRINTER_ERROR_BASE + 11)
#define PRINTER_PARAM_DELETE_NULL_POINTER         (PRINTER_ERROR_BASE + 12)

#define PRINTER_LL_ADD_NULL_POINTER               (PRINTER_ERROR_BASE + 20)
#define PRINTER_LL_ADD_NULL_HANDLE                (PRINTER_ERROR_BASE + 21)


#define PRINTER_LL_POP_NULL_HANDLE                (PRINTER_ERROR_BASE + 23)
#define PRINTER_LL_POP_NULL_POP_HANDLE            (PRINTER_ERROR_BASE + 24)


#define PRINTER_LL_GET_INST_NULL_HANDLE           (PRINTER_ERROR_BASE + 26)
#define PRINTER_LL_GET_INST_NULL_HEADER           (PRINTER_ERROR_BASE + 27)
#define PRINTER_LL_GET_INST_NULL_INFO_POINTER     (PRINTER_ERROR_BASE + 28)
#define PRINTER_LL_GET_INST_WRONG_INFO_POINTER    (PRINTER_ERROR_BASE + 29)

#define PRINTER_LL_DEL_INST_NULL_POINTER          (PRINTER_ERROR_BASE + 30)
#define PRINTER_LL_DEL_INST_NULL_HANDLE           (PRINTER_ERROR_BASE + 31)
#define PRINTER_LL_DEL_INST_NULL_INFO_POINTER     (PRINTER_ERROR_BASE + 32)
#define PRINTER_LL_DEL_INST_WRONG_INFO_POINTER    (PRINTER_ERROR_BASE + 33)


#define PRINTER_LL_GET_LAST_NULL_HANDLE           (PRINTER_ERROR_BASE + 34)

#define PRINTER_LL_GET_INFO_PTR_NULL_HANDLE       (PRINTER_ERROR_BASE + 35)

#define PRINTER_LL_GET_PRE_PTR_NULL_POINTER       (PRINTER_ERROR_BASE + 36)
#define PRINTER_LL_GET_PRE_PTR_INFO_NULL_POINTER  (PRINTER_ERROR_BASE + 37)
#define PRINTER_LL_DEL_ALL_NULL_POINTER           (PRINTER_ERROR_BASE + 38)


#define PRINTER_PRNLL_DEL_ALL_NULL_POINTER        (PRINTER_ERROR_BASE + 50)

#define PRINTER_FLAG_NEW_NULL_POINTER             (PRINTER_ERROR_BASE + 60)
#define PRINTER_FLAG_SET_NULL_POINTER             (PRINTER_ERROR_BASE + 61)
#define PRINTER_FLAG_SET_WRONG_OPTION             (PRINTER_ERROR_BASE + 62)
#define PRINTER_FLAG_CHECK_NULL_POINTER           (PRINTER_ERROR_BASE + 63)
#define PRINTER_FLAG_CHECK_WRONG_OPTION           (PRINTER_ERROR_BASE + 64)
#define PRINTER_FLAG_FLUSH_NULL_POINTER           (PRINTER_ERROR_BASE + 65)

#define PRINTER_QUEUE_NEW_NULL_POINTER            (PRINTER_ERROR_BASE + 70)
#define PRINTER_QUEUE_NEW_WRONG_PARAMETER         (PRINTER_ERROR_BASE + 71)
#define PRINTER_QUEUE_ADD_NULL_POINTER            (PRINTER_ERROR_BASE + 72)
#define PRINTER_QUEUE_ADD_QUEUE_FULL              (PRINTER_ERROR_BASE + 73)
#define PRINTER_QUEUE_ADD_FRONT_NULL_POINTER      (PRINTER_ERROR_BASE + 74)
#define PRINTER_QUEUE_ADD_FRONT_QUEUE_FULL        (PRINTER_ERROR_BASE + 75)
#define PRINTER_QUEUE_GET_NULL_POINTER            (PRINTER_ERROR_BASE + 76)
#define PRINTER_QUEUE_GET_QUEUE_EMPTY             (PRINTER_ERROR_BASE + 77)
#define PRINTER_QUEUE_FLUSH_NULL_POINTER          (PRINTER_ERROR_BASE + 78)







#define PRINTER_MOTOR_ERROR_BASE              (PRINTER_ERROR_BASE + 100)
#define PRINTER_MOTOR_CONFLICT                (PRINTER_MOTOR_ERROR_BASE + 1)   // request motor on, but motor on dec process
#define PRINTER_MOTOR_DRIVER_INIT_FAIL        (PRINTER_MOTOR_ERROR_BASE + 2) 
#define PRINTER_MOTOR_REG_SPACE_FULL          (PRINTER_MOTOR_ERROR_BASE + 3)
#define PRINTER_MOTOR_REG_WRONG_PARAMETER     (PRINTER_MOTOR_ERROR_BASE + 4)
#define PRINTER_MOTOR_SET_DIR_FAIL            (PRINTER_MOTOR_ERROR_BASE + 5)
#define PRINTER_MOTOR_CHANGE_STEP_TYPE_FAIL   (PRINTER_MOTOR_ERROR_BASE + 6)
#define PRINTER_MOTOR_TIMER_RESET_FAIL        (PRINTER_MOTOR_ERROR_BASE + 7)
#define PRINTER_MOTOR_TIMER_NEW_FAIL          (PRINTER_MOTOR_ERROR_BASE + 8)
#define PRINTER_MOTOR_POLYGON_OFF_FAIL        (PRINTER_MOTOR_ERROR_BASE + 9)
#define PRINTER_MOTOR_NOT_FOUND               (PRINTER_MOTOR_ERROR_BASE + 10)
#define PRINTER_MOTOR_SET_ILLEGAL_MOTOR       (PRINTER_MOTOR_ERROR_BASE + 11)
#define PRINTER_MOTOR_TIMER_CHANGE_FAIL       (PRINTER_MOTOR_ERROR_BASE + 12)
#define PRINTER_MOTOR_SET_WRONG_VALUE         (PRINTER_MOTOR_ERROR_BASE + 13)
#define PRINTER_MOTOR_POLYGON_ON_FAIL         (PRINTER_MOTOR_ERROR_BASE + 14)
#define PRINTER_MOTOR_MOPWN_ON_NOW_STEP_FAIL    (PRINTER_MOTOR_ERROR_BASE + 15)
#define PRINTER_MOTOR_MOPWN_OFF_PPS_COUNT_FAIL  (PRINTER_MOTOR_ERROR_BASE + 16)
#define PRINTER_MOTOR_MOTDRV_GETACC_MOT_ID_FAIL (PRINTER_MOTOR_ERROR_BASE + 17)
#define PRINTER_MOTOR_MOTDRV_PWM_RES_IND_FAIL   (PRINTER_MOTOR_ERROR_BASE + 18)
#define PRINTER_MOTOR_MOTDRV_SW_PWM_SPD_LEVEL_FAIL   (PRINTER_MOTOR_ERROR_BASE + 19)
#define PRINTER_MOTOR_MOTDRV_SW_PWM_MOTOR_FAIL  (PRINTER_MOTOR_ERROR_BASE + 20)
#define PRINTER_MOTOR_MOTDRV_GET_MS_MOTOR_FAIL  (PRINTER_MOTOR_ERROR_BASE + 21)
#define PRINTER_MOTOR_MOTDRV_USE_PRI_FAIL       (PRINTER_MOTOR_ERROR_BASE + 22)
#define PRINTER_MOTOR_GET_MEM_FAIL	            (PRINTER_MOTOR_ERROR_BASE + 23)
#define PRINTER_MOTOR_PROC_SW_SPD_GET_AGAIN     (PRINTER_MOTOR_ERROR_BASE + 24)
#define PRINTER_MOTOR_SW_SPD_PARA_SAME          (PRINTER_MOTOR_ERROR_BASE + 25)
#define PRINTER_MOTOR_SET_FPGA_CLK_INDEX_FAIL   (PRINTER_MOTOR_ERROR_BASE + 26)
#define PRINTER_MOTOR_REG_INIT_NO_FINISH        (PRINTER_MOTOR_ERROR_BASE + 27)
#define PRINTER_MOTOR_REG_CALLBACK_NULL         (PRINTER_MOTOR_ERROR_BASE + 28)
#define PRINTER_MOTOR_REG_MOTOR_INDEX_FAIL      (PRINTER_MOTOR_ERROR_BASE + 29)
#define PRINTER_MOTOR_SWACT_NO_SUPPORT_POLYGON  (PRINTER_MOTOR_ERROR_BASE + 30)
#define PRINTER_MOTOR_SWACT_NOW_STATE_ERROR     (PRINTER_MOTOR_ERROR_BASE + 31)
#define PRINTER_MOTOR_SWACT_OTHER_SN_UNI        (PRINTER_MOTOR_ERROR_BASE + 32)
#define PRINTER_MOTOR_SWACT_BUSY_SET_GO         (PRINTER_MOTOR_ERROR_BASE + 33)
#define PRINTER_MOTOR_CHANGE_PPS_NO_SUPPORT     (PRINTER_MOTOR_ERROR_BASE + 34)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_7   (PRINTER_MOTOR_ERROR_BASE + 35)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_6   (PRINTER_MOTOR_ERROR_BASE + 36)
#define PRINTER_MOTOR_SN_NO_REGISTER            (PRINTER_MOTOR_ERROR_BASE + 37)
#define PRINTER_MOTOR_FIX_RUN_STATE_NOT_READY   (PRINTER_MOTOR_ERROR_BASE + 38)
#define PRINTER_MOTOR_FIX_ALREADY_USE           (PRINTER_MOTOR_ERROR_BASE + 39)
#define PRINTER_MOTOR_FIX_NOT_RUNNING_SET_OFF   (PRINTER_MOTOR_ERROR_BASE + 40)
#define PRINTER_MOTOR_LOCK_OTHER_SN_LOCK        (PRINTER_MOTOR_ERROR_BASE + 41)
#define PRINTER_MOTOR_REQ_INIT_NOT_FINISH       (PRINTER_MOTOR_ERROR_BASE + 42)
#define PRINTER_MOTOR_REQ_MOTOR_INDEX_ERROR     (PRINTER_MOTOR_ERROR_BASE + 43)
#define PRINTER_MOTOR_REQ_SW_INDEX_ERROR        (PRINTER_MOTOR_ERROR_BASE + 44)
#define PRINTER_MOTOR_REQ_USE_TYPE_INDEX_ERROR  (PRINTER_MOTOR_ERROR_BASE + 45)
#define PRINTER_MOTOR_REQ_SPD_LEVEL_INDEX_ERROR (PRINTER_MOTOR_ERROR_BASE + 46)
#define PRINTER_MOTOR_REQ_SPD_CHANGE_RUN_MOTOR  (PRINTER_MOTOR_ERROR_BASE + 47)
#define PRINTER_MOTOR_REQ_OTHER_SN_LOCK         (PRINTER_MOTOR_ERROR_BASE + 48)
#define PRINTER_MOTOR_SET_DIR_STATE_UNI         (PRINTER_MOTOR_ERROR_BASE + 49)
#define PRINTER_MOTOR_SET_DIR_STATE_NORMAL      (PRINTER_MOTOR_ERROR_BASE + 50)
#define PRINTER_MOTOR_ENG_STEPTYPE_NO_SUPPORT   (PRINTER_MOTOR_ERROR_BASE + 51)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_1   (PRINTER_MOTOR_ERROR_BASE + 52)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_2   (PRINTER_MOTOR_ERROR_BASE + 53)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_3   (PRINTER_MOTOR_ERROR_BASE + 54)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_4   (PRINTER_MOTOR_ERROR_BASE + 55)
#define PRINTER_MOTOR_CHANGE_PPS_SIZE_ERROR_5   (PRINTER_MOTOR_ERROR_BASE + 56)

#define PRINTER_MOTOR_CONF_BUSY_SET_GO_OPC          (PRINTER_MOTOR_ERROR_BASE + 57)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 58)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 59)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_FUSER        (PRINTER_MOTOR_ERROR_BASE + 60)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_TONER        (PRINTER_MOTOR_ERROR_BASE + 61)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_EXIT         (PRINTER_MOTOR_ERROR_BASE + 62)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 63)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 64)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 65)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 66)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 67)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 68)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 69)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 70)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 71)

#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_OPC          (PRINTER_MOTOR_ERROR_BASE + 72)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 73)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 74)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_FUSER        (PRINTER_MOTOR_ERROR_BASE + 75)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_TONER        (PRINTER_MOTOR_ERROR_BASE + 76)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_EXIT         (PRINTER_MOTOR_ERROR_BASE + 77)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 78)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 79)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 80)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 81)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 82)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 83)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 84)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 85)
#define PRINTER_MOTOR_CONF__UNI_BUSY_SET_ACT_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 86)

#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_OPC          (PRINTER_MOTOR_ERROR_BASE + 87)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 88)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 89)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_FUSER        (PRINTER_MOTOR_ERROR_BASE + 90)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_TONER        (PRINTER_MOTOR_ERROR_BASE + 91)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_EXIT         (PRINTER_MOTOR_ERROR_BASE + 92)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 93)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 94)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 95)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 96)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 97)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 98)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 99)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 100)
#define PRINTER_MOTOR_CONF_UNI_SET_NORMAL_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 101)

#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_OPC          (PRINTER_MOTOR_ERROR_BASE + 102)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 103)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 104)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_FUSER        (PRINTER_MOTOR_ERROR_BASE + 105)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_TONER        (PRINTER_MOTOR_ERROR_BASE + 106)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_EXIT         (PRINTER_MOTOR_ERROR_BASE + 107)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 108)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 109)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 110)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 111)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 112)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 113)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 114)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 115)
#define PRINTER_MOTOR_CONF_UNI_WRONG_ID_ACT_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 116)

#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_OPC          (PRINTER_MOTOR_ERROR_BASE + 117)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 118)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 119)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_FUSER        (PRINTER_MOTOR_ERROR_BASE + 120)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_TONER        (PRINTER_MOTOR_ERROR_BASE + 121)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_EXIT         (PRINTER_MOTOR_ERROR_BASE + 122)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 123)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 124)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 125)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 126)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 127)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 128)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 129)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 130)
#define PRINTER_MOTOR_CONF_UNI_WRONG_SPD_LEVEL_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 131)

#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_OPC          (PRINTER_MOTOR_ERROR_BASE + 132)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 133)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 134)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_FUSER        (PRINTER_MOTOR_ERROR_BASE + 135)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_TONER        (PRINTER_MOTOR_ERROR_BASE + 136)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_EXIT         (PRINTER_MOTOR_ERROR_BASE + 137)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 138)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 139)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 140)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 141)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 142)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 143)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 144)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 145)
#define PRINTER_MOTOR_CONF_NORMAL_SET_UNI_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 146)

#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_OPC          (PRINTER_MOTOR_ERROR_BASE + 147)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_PICKUP       (PRINTER_MOTOR_ERROR_BASE + 148)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_DESKEW       (PRINTER_MOTOR_ERROR_BASE + 149)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_FUSER        (PRINTER_MOTOR_ERROR_BASE + 150)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_TONER        (PRINTER_MOTOR_ERROR_BASE + 151)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_EXIT         (PRINTER_MOTOR_ERROR_BASE + 152)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_MANUAL       (PRINTER_MOTOR_ERROR_BASE + 153)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_DUPLEX       (PRINTER_MOTOR_ERROR_BASE + 154)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_CAS2PICKUP   (PRINTER_MOTOR_ERROR_BASE + 155)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_CAS2DESKEW   (PRINTER_MOTOR_ERROR_BASE + 156)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_CAS2LIFTUP   (PRINTER_MOTOR_ERROR_BASE + 157)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_LIFTUP       (PRINTER_MOTOR_ERROR_BASE + 158)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_POLYGON      (PRINTER_MOTOR_ERROR_BASE + 159)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_CAS3PICKUP   (PRINTER_MOTOR_ERROR_BASE + 160)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_CAS4PICKUP   (PRINTER_MOTOR_ERROR_BASE + 161)

#define PRINTER_MOTOR_MOTDRV_PWM_RES_KIND_FAIL			(PRINTER_MOTOR_ERROR_BASE + 162)
//for MICE
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_MAIN_M			(PRINTER_MOTOR_ERROR_BASE + 163)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_EXIT_M			(PRINTER_MOTOR_ERROR_BASE + 164)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_POLYGON_M		(PRINTER_MOTOR_ERROR_BASE + 165)
#define PRINTER_MOTOR_CONF_BUSY_SET_GO_SHIFT_M			(PRINTER_MOTOR_ERROR_BASE + 166)

#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_MAIN_M		(PRINTER_MOTOR_ERROR_BASE + 167)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_EXIT_M		(PRINTER_MOTOR_ERROR_BASE + 168)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_POLYGON_M	(PRINTER_MOTOR_ERROR_BASE + 169)
#define PRINTER_MOTOR_CONF_WRONG_SPD_LEVEL_SHIFT_M		(PRINTER_MOTOR_ERROR_BASE + 170)

#define PRINTER_MOTOR_CONF_STATE_ABNORMAL_MAIN_M		(PRINTER_MOTOR_ERROR_BASE + 167)
#define PRINTER_MOTOR_CONF_STATE_ABNORMAL_EXIT_M		(PRINTER_MOTOR_ERROR_BASE + 168)
#define PRINTER_MOTOR_CONF_STATE_ABNORMAL_POLYGON_M		(PRINTER_MOTOR_ERROR_BASE + 169)
#define PRINTER_MOTOR_CONF_STATE_ABNORMAL_SHIFT_M		(PRINTER_MOTOR_ERROR_BASE + 170)

#define PRINTER_MOTOR_SET_DIR_STATE_UNI_MAIN_M			(PRINTER_MOTOR_ERROR_BASE + 171)
#define PRINTER_MOTOR_SET_DIR_STATE_UNI_EXIT_M			(PRINTER_MOTOR_ERROR_BASE + 172)
#define PRINTER_MOTOR_SET_DIR_STATE_UNI_POLYGON_M		(PRINTER_MOTOR_ERROR_BASE + 173)
#define PRINTER_MOTOR_SET_DIR_STATE_UNI_SHIFT_M			(PRINTER_MOTOR_ERROR_BASE + 174)

#define PRINTER_MOTOR_SET_DIR_STATE_NORMAL_MAIN_M		(PRINTER_MOTOR_ERROR_BASE + 175)
#define PRINTER_MOTOR_SET_DIR_STATE_NORMAL_EXIT_M		(PRINTER_MOTOR_ERROR_BASE + 176)
#define PRINTER_MOTOR_SET_DIR_STATE_NORMAL_POLYGON_M	(PRINTER_MOTOR_ERROR_BASE + 177)
#define PRINTER_MOTOR_SET_DIR_STATE_NORMAL_SHIFT_M		(PRINTER_MOTOR_ERROR_BASE + 178)

#define PRINTER_MOTOR_SWACT_BUSY_SET_GO_MAIN_M			(PRINTER_MOTOR_ERROR_BASE + 179)
#define PRINTER_MOTOR_SWACT_BUSY_SET_GO_EXIT_M			(PRINTER_MOTOR_ERROR_BASE + 180)
#define PRINTER_MOTOR_SWACT_BUSY_SET_GO_POLYGON_M		(PRINTER_MOTOR_ERROR_BASE + 181)
#define PRINTER_MOTOR_SWACT_BUSY_SET_GO_SHIFT_M			(PRINTER_MOTOR_ERROR_BASE + 182)

#define PRINTER_MOTOR_SWACT_OTHER_SN_UNI_MAIN_M			(PRINTER_MOTOR_ERROR_BASE + 183)
#define PRINTER_MOTOR_SWACT_OTHER_SN_UNI_EXIT_M			(PRINTER_MOTOR_ERROR_BASE + 184)
#define PRINTER_MOTOR_SWACT_OTHER_SN_UNI_POLYGON_M		(PRINTER_MOTOR_ERROR_BASE + 185)
#define PRINTER_MOTOR_SWACT_OTHER_SN_UNI_SHIFT_M		(PRINTER_MOTOR_ERROR_BASE + 186)
#define PRINTER_MOTOR_PRIPWM_INDEX_OUT_OF_RANGE			(PRINTER_MOTOR_ERROR_BASE + 187)
#define PRINTER_MOTOR_INIT_FINISH_NOTIFY_CALLBACK_NULL	(PRINTER_MOTOR_ERROR_BASE + 188)

#define PRINTER_MOTOR_INIT_FINISH_NOTIFY_COUNT_FULL		(PRINTER_MOTOR_ERROR_BASE + 189)
   
#define PRINTER_TIMER_ERROR_BASE             (PRINTER_ERROR_BASE + 300)
#define PRINTER_TIMER_ARRAY_FULL             (PRINTER_TIMER_ERROR_BASE + 1)
#define PRINTER_TIMER_PARAMETER_WRONG        (PRINTER_TIMER_ERROR_BASE + 2)
#define PRINTER_TIMER_EXCEED_MAX_REQ         (PRINTER_TIMER_ERROR_BASE + 3)
#define PRINTER_TIMER_CHANGE_REQ_ID_FAIL     (PRINTER_TIMER_ERROR_BASE + 4)
#define PRINTER_TIMER_PAUSE_ID_FAIL          (PRINTER_TIMER_ERROR_BASE + 5)
#define PRINTER_TIMER_PAUSE_ID_NO_USE        (PRINTER_TIMER_ERROR_BASE + 6)
#define PRINTER_TIMER_CONTINUE__ID_FAIL      (PRINTER_TIMER_ERROR_BASE + 7)
#define PRINTER_TIMER_CONTINUE_ID_NO_USE     (PRINTER_TIMER_ERROR_BASE + 8)
#define PRINTER_TIMER_CLEAR_ID_FAIL          (PRINTER_TIMER_ERROR_BASE + 9)
#define PRINTER_TIMER_RESET_ID_FAIL          (PRINTER_TIMER_ERROR_BASE + 10)




#define PRINTER_SENSOR_ERROR_BASE            (PRINTER_ERROR_BASE + 400)
#define PRINTER_SENSOR_ARRAY_FULL            (PRINTER_SENSOR_ERROR_BASE + 1)
#define PRINTER_SENSOR_WRONG_SENSOR          (PRINTER_SENSOR_ERROR_BASE + 2)
#define PRINTER_SENSOR_MAPPING_FAIL          (PRINTER_SENSOR_ERROR_BASE + 3)
#define PRINTER_SENSOR_REG_COUNT_MAX         (PRINTER_SENSOR_ERROR_BASE + 4)
#define PRINTER_SENSOR_WRONG_TYPE            (PRINTER_SENSOR_ERROR_BASE + 5)
#define PRINTER_SENSOR_SETMASKINFO_IND_FAIL  (PRINTER_SENSOR_ERROR_BASE + 6)
#define PRINTER_SENSOR_REG_FUNC_NULL         (PRINTER_SENSOR_ERROR_BASE + 7)
#define PRINTER_SENSOR_REGD_FUNC_NULL        (PRINTER_SENSOR_ERROR_BASE + 8)
#define PRINTER_SENSOR_REG_ID_EXCEED         (PRINTER_SENSOR_ERROR_BASE + 9)
#define PRINTER_SENSOR_REGD_ID_EXCEED        (PRINTER_SENSOR_ERROR_BASE + 10)
#define PRINTER_SENSOR_REGD_EXCEED_REG_COUNT (PRINTER_SENSOR_ERROR_BASE + 11)
#define PRINTER_SENSOR_GET_STAT_ID_FAIL      (PRINTER_SENSOR_ERROR_BASE + 12)
#define PRINTER_SENSOR_GET_STAT_IND_ID_FAIL  (PRINTER_SENSOR_ERROR_BASE + 13)
#define PRINTER_SENSOR_GET_TYPE_ID_FAIL      (PRINTER_SENSOR_ERROR_BASE + 14)
#define PRINTER_SENSOR_REGD_NO_MATCH_SEN     (PRINTER_SENSOR_ERROR_BASE + 15)
#define PRINTER_SENSOR_WRONG_SEN_TYPE        (PRINTER_SENSOR_ERROR_BASE + 16)


#define PRINTER_INTRAY_ERROR_BASE            (PRINTER_ERROR_BASE + 500)
#define PRINTER_INTRAY_EX_REG_SEN_FUNC_NULL  (PRINTER_INTRAY_ERROR_BASE + 1)
#define PRINTER_INTRAY_EX_REG_SEN_EXCEED_MAX (PRINTER_INTRAY_ERROR_BASE + 2)
#define PRINTER_INTRAY_EX_CMD_FAIL	     (PRINTER_INTRAY_ERROR_BASE + 3)
#define PRINTER_INTRAY_EX_SET_MOTOR_FAIL     (PRINTER_INTRAY_ERROR_BASE + 4)
#define PRINTER_INTRAY_EX_CHG_SPD_NO_34TRAY  (PRINTER_INTRAY_ERROR_BASE + 5)
#define PRINTER_INTRAY_INIT_NOT_FINISH       (PRINTER_INTRAY_ERROR_BASE + 6)

#define PRINTER_EP_ERROR_BASE               		(PRINTER_ERROR_BASE + 600)
#define PRINTER_EP_SET_WRONG_ENG_STATE              (PRINTER_EP_ERROR_BASE + 1)
#define PRINTER_EP_SET_IMAGE_PRINT_TYPE_ERROR       (PRINTER_EP_ERROR_BASE + 2)
#define PRINTER_EP_SET_IMAGE_INPUT_TRAY_ERROR       (PRINTER_EP_ERROR_BASE + 3)
#define PRINTER_EP_SET_IMAGE_EP_STATE_ERROR         (PRINTER_EP_ERROR_BASE + 4)
#define PRINTER_EP_PAGE_END_PRINT_TYPE_ERROR        (PRINTER_EP_ERROR_BASE + 5)
#define PRINTER_EP_EP_TIMING_STATE_INCORRECT        (PRINTER_EP_ERROR_BASE + 6)
#define PRINTER_EP_POLYGON_MOTOR_ON_STATUS_ERROR   	(PRINTER_EP_ERROR_BASE + 7)
#define PRINTER_EP_POLYGON_MOTOR_OFF_STATUS_ERROR   (PRINTER_EP_ERROR_BASE + 8)
#define PRINTER_RPC_HIV_ACTION_INDEX_ERROR	        (PRINTER_EP_ERROR_BASE + 9)
#define PRINTER_LPH_COMP_FAIL                		(PRINTER_EP_ERROR_BASE + 10)
#define PRINTER_LPH_COMP_WRONG_PARAM            	(PRINTER_EP_ERROR_BASE + 11)
#define PRINTER_LPH_COMP_READ_DATA_FAIL            	(PRINTER_EP_ERROR_BASE + 12)
#define PRINTER_HIV_TYPE_ERROR            			(PRINTER_EP_ERROR_BASE + 13)
#define PRINTER_RPC_HIV_TRANS_DATA_CONFLICT_ERROR   (PRINTER_EP_ERROR_BASE + 14)
#define PRINTER_RPC_START_LSU_DMA_NOT_READY         (PRINTER_EP_ERROR_BASE + 15)
#define PRINTER_EP_SET_WRONG_ENG_ACTION             (PRINTER_EP_ERROR_BASE + 16)

#define PRINTER_ENG_PARAM_ERROR_BASE               					(PRINTER_ERROR_BASE + 650)
#define PRINTER_ENG_PARAM_REG_STATE_NULL_PARAM      				(PRINTER_ENG_PARAM_ERROR_BASE + 1)
#define PRINTER_ENG_PARAM_CALI_DATA_OVER_SPEC       				(PRINTER_ENG_PARAM_ERROR_BASE + 2)
#define PRINTER_ENG_PARAM_SET_CALI_DATA_TRAY_TYPE_ERROR 			(PRINTER_ENG_PARAM_ERROR_BASE + 3)
#define PRINTER_ENG_PARAM_SET_CALI_DATA_CALI_TYPE_ERROR 			(PRINTER_ENG_PARAM_ERROR_BASE + 4)
#define PRINTER_ENG_PARAM_GET_DEVICE_VALUE_DEVICE_TYPE_ERROR 		(PRINTER_ENG_PARAM_ERROR_BASE + 5)
#define PRINTER_ENG_PARAM_GET_DEVICE_VALUE_DEVICE_INFO_ERROR 		(PRINTER_ENG_PARAM_ERROR_BASE + 6)
#define PRINTER_ENG_PARAM_SET_DEVICE_VALUE_DEVICE_TYPE_ERROR 		(PRINTER_ENG_PARAM_ERROR_BASE + 7)
#define PRINTER_ENG_PARAM_SET_DEVICE_VALUE_DEVICE_INFO_ERROR 		(PRINTER_ENG_PARAM_ERROR_BASE + 8)
#define PRINTER_ENG_PARAM_GET_DEVICE_STRVALUE_DEVICE_TYPE_ERROR 	(PRINTER_ENG_PARAM_ERROR_BASE + 9)
#define PRINTER_ENG_PARAM_GET_DEVICE_STRVALUE_DEVICE_INFO_ERROR 	(PRINTER_ENG_PARAM_ERROR_BASE + 10)
#define PRINTER_ENG_PARAM_SET_DEVICE_STRVALUE_DEVICE_TYPE_ERROR 	(PRINTER_ENG_PARAM_ERROR_BASE + 11)
#define PRINTER_ENG_PARAM_SET_DEVICE_STRVALUE_DEVICE_INFO_ERROR 	(PRINTER_ENG_PARAM_ERROR_BASE + 12)
#define PRINTER_ENG_PARAM_WRITE_ENG_PARAM_TYPE_ERROR			 	(PRINTER_ENG_PARAM_ERROR_BASE + 13)
#define PRINTER_ENG_PARAM_SET_CALI_USING_DATA_TRAY_TYPE_ERROR 		(PRINTER_ENG_PARAM_ERROR_BASE + 14)
#define PRINTER_ENG_PARAM_SET_VMAG_VALUE_ERROR                      (PRINTER_ENG_PARAM_ERROR_BASE + 15)  
#define PRINTER_ENG_PARAM_SET_CALI_GROUP_ERROR						 (PRINTER_ENG_PARAM_ERROR_BASE + 16)
#define PRINTER_FUSER_ERROR_BASE                    (PRINTER_ERROR_BASE + 700)
#define PRINTER_FUSER_CALI_FAIL                     (PRINTER_FUSER_ERROR_BASE + 1)
#define PRINTER_FUSER_SET_STATE_PARAM_ERROR         (PRINTER_FUSER_ERROR_BASE + 2)
#define PRINTER_FUSER_SET_ACTIVE_TEMP_WRONG_STATE	(PRINTER_FUSER_ERROR_BASE + 3)
#define PRINTER_FUSER_GAP_SMALL_DESKEW_TO_FUSER		(PRINTER_FUSER_ERROR_BASE + 4)
#define PRINTER_FUSER_MTC_WRONG_FUSER_TEMP_TYPE		(PRINTER_FUSER_ERROR_BASE + 5)
#define PRINTER_FUSER_REG_TEMP_COUNT_FULL				(PRINTER_FUSER_ERROR_BASE + 6)
#define PRINTER_FUSER_SET_TEMP_REPORT_SW_SN_FAIL		(PRINTER_FUSER_ERROR_BASE + 7)

#define PRINTER_PP_ERROR_BASE                       (PRINTER_ERROR_BASE + 800)
#define PRINTER_PP_PICKUP_NULL_POINTER              (PRINTER_PP_ERROR_BASE + 1)
#define PRINTER_PP_SET_TIMER_JAM_NULL_POINTER       (PRINTER_PP_ERROR_BASE + 2)
#define PRINTER_PP_SPARE_JAM_NULL_POINTER           (PRINTER_PP_ERROR_BASE + 3)
#define PRINTER_PP_REG_JAM_NULL_POINTER             (PRINTER_PP_ERROR_BASE + 4)
#define PRINTER_PP_FUSER_OUT_JAM_NULL_POINTER       (PRINTER_PP_ERROR_BASE + 5)
#define PRINTER_PP_EXIT_JAM_NULL_POINTER            (PRINTER_PP_ERROR_BASE + 6)
#define PRINTER_PP_DUPLEX_JAM_NULL_POINTER          (PRINTER_PP_ERROR_BASE + 7)
#define PRINTER_PP_DUPLEX_DESKEW_JAM_NULL_POINTER   (PRINTER_PP_ERROR_BASE + 8)
#define PRINTER_PP_CAS2_DESKEW_JAM_NULL_POINTER     (PRINTER_PP_ERROR_BASE + 9)
#define PRINTER_PP_CAS3_DESKEW_JAM_NULL_POINTER     (PRINTER_PP_ERROR_BASE + 10)
#define PRINTER_PP_CAS4_DESKEW_JAM_NULL_POINTER     (PRINTER_PP_ERROR_BASE + 11)
#define PRINTER_PP_MANUAL_TRAY_JAM_NULL_POINTER     (PRINTER_PP_ERROR_BASE + 12)
#define PRINTER_PP_MAIN_TRAY_JAM_NULL_POINTER       (PRINTER_PP_ERROR_BASE + 13)
#define PRINTER_PP_2ND_TRAY_JAM_NULL_POINTER        (PRINTER_PP_ERROR_BASE + 14)
#define PRINTER_PP_3RD_TRAY_JAM_NULL_POINTER        (PRINTER_PP_ERROR_BASE + 15)
#define PRINTER_PP_4TH_TRAY_JAM_NULL_POINTER        (PRINTER_PP_ERROR_BASE + 16)

#define PRINTER_PP_SET_TIMER_INVALID_NULL_POINTER   (PRINTER_PP_ERROR_BASE + 17)
#define PRINTER_PP_PRN_REQ_NULL_PACKAGE_POINTER     (PRINTER_PP_ERROR_BASE + 18)

#define PRINTER_PP_DESKEW_WRONG_INPUT               (PRINTER_PP_ERROR_BASE + 20)
#define PRINTER_PP_GET_LAST_WRONG_FLOW              (PRINTER_PP_ERROR_BASE + 21)
#define PRINTER_PP_JAM_WRONG_LOCATION               (PRINTER_PP_ERROR_BASE + 22)
#define PRINTER_PP_SET_PICKUP_FLAG_WRONG_IT         (PRINTER_PP_ERROR_BASE + 23)
#define PRINTER_PP_SET_TIMER_JAM_WRONG_LOC          (PRINTER_PP_ERROR_BASE + 24)
#define PRINTER_PP_SET_TIMER_INVALID_WRONG_LOC      (PRINTER_PP_ERROR_BASE + 25)
#define PRINTER_PP_SET_TIMER_DESKEW_WRONG_IT        (PRINTER_PP_ERROR_BASE + 26)
#define PRINTER_PP_REQ_RECEIVE_WRONG_SIZE           (PRINTER_PP_ERROR_BASE + 27)
#define PRINTER_PP_REQ_RECEIVE_WRONG_STRATEGY       (PRINTER_PP_ERROR_BASE + 28)
#define PRINTER_PP_REQ_RECEIVE_WRONG_IT             (PRINTER_PP_ERROR_BASE + 29)
#define PRINTER_PP_SEND_TO_PATH_WRONG_IT            (PRINTER_PP_ERROR_BASE + 30)


#define PRINTER_PP_ENV_CHANGE_TIME_OUT              (PRINTER_PP_ERROR_BASE + 40)
#define PRINTER_PP_READY_STATE_PRN_REQ_SUSPEND      (PRINTER_PP_ERROR_BASE + 41)

#define PRINTER_PP_SEND_PRN_REQ_ENG_NOT_AVAILABLE       (PRINTER_PP_ERROR_BASE + 50)
#define PRINTER_PP_SET_TIMER_JAM_WRONG_PARAMETER        (PRINTER_PP_ERROR_BASE + 51)
#define PRINTER_PP_SET_TIMER_PICKUP_OFF_WRONG_IT        (PRINTER_PP_ERROR_BASE + 52)
#define PRINTER_PP_SET_TIMER_PICKUP_OFF_WRONG_LENGTH    (PRINTER_PP_ERROR_BASE + 53)
#define PRINTER_PP_SET_ENG_IT_MODE_NOT_AVAILABLE        (PRINTER_PP_ERROR_BASE + 54)

#define PRINTER_PP_SHIFT_MOTOR_TO_LEFT_STATE_ERROR    (PRINTER_PP_ERROR_BASE + 60)
#define PRINTER_PP_SHIFT_MOTOR_TO_MIDDLE_STATE_ERROR  (PRINTER_PP_ERROR_BASE + 61)
#define PRINTER_PP_CB_SHIFT_MOTOR_TO_M_TIME_OUT       (PRINTER_PP_ERROR_BASE + 62)
#define PRINTER_PP_MAINFEED_JAM_NULL_POINTER          (PRINTER_PP_ERROR_BASE + 63)
#define PRINTER_PP_TRAY_JAM_NULL_POINTER              (PRINTER_PP_ERROR_BASE + 64)


#define PRINTER_SC_ERROR_BASE                        (PRINTER_ERROR_BASE + 900)

#define PRINTER_SC_CANCEL_SET_WRONG_STATE            (PRINTER_SC_ERROR_BASE + 20)
#define PRINTER_SC_SLEEP_SET_WRONG_STATE             (PRINTER_SC_ERROR_BASE + 21)
#define PRINTER_SC_WAKEUP_SET_WRONG_STATE            (PRINTER_SC_ERROR_BASE + 22)
#define PRINTER_SC_REQ_CHG_ENV_WRONG_STATE           (PRINTER_SC_ERROR_BASE + 23)
#define PRINTER_SC_24V_ON_TIMER_SET_WRONG_FLOW       (PRINTER_SC_ERROR_BASE + 24)
#define PRINTER_SC_24V_ON_TIMER_CALLBACK_WRONG_FLOW  (PRINTER_SC_ERROR_BASE + 25)
#define PRINTER_SC_24V_OFF_TIMER_SET_WRONG_FLOW      (PRINTER_SC_ERROR_BASE + 26)
#define PRINTER_SC_24V_OFF_TIMER_CALLBACK_WRONG_FLOW (PRINTER_SC_ERROR_BASE + 27)

#define PRINTER_SC_REQ_ACTIVE_ENG_NOT_AVAILABLE     (PRINTER_SC_ERROR_BASE + 40)
#define PRINTER_SC_PRE_FUSING_ENG_NOT_AVAILABLE     (PRINTER_SC_ERROR_BASE + 41)
#define PRINTER_SC_SET_ENG_IT_MODE_NOT_AVAILABLE    (PRINTER_SC_ERROR_BASE + 42)

#define PRINTER_ENGFW_SET_PRN_ENG_NOT_AVAILABLE     (PRINTER_SC_ERROR_BASE + 50)
#define PRINTER_ENGFW_SET_PRN_WRONG_IT              (PRINTER_SC_ERROR_BASE + 51)
#define PRINTER_ENGFW_SET_PRN_WRONG_LENGTH          (PRINTER_SC_ERROR_BASE + 52)
#define PRINTER_ENGFW_SET_PRN_WRONG_WIDTH           (PRINTER_SC_ERROR_BASE + 53)
#define PRINTER_ENGFW_SET_PRN_WRONG_REQ_MODE        (PRINTER_SC_ERROR_BASE + 54)
#define PRINTER_ENGFW_SET_PRN_WRONG_RES             (PRINTER_SC_ERROR_BASE + 55)
#define PRINTER_ENGFW_SET_PRN_LINK_NULL             (PRINTER_SC_ERROR_BASE + 56)
#define PRINTER_ENGFW_SET_PRN_PACKAGE_NULL          (PRINTER_SC_ERROR_BASE + 57)
#define PRINTER_ENGFW_SET_PRN_BACK_IMG_NULL         (PRINTER_SC_ERROR_BASE + 58)
#define PRINTER_ENGFW_SET_PRN_FRONT_IMG_NULL        (PRINTER_SC_ERROR_BASE + 59)
#define PRINTER_ENGFW_SET_PRN_REQ_NULL              (PRINTER_SC_ERROR_BASE + 60)
#define PRINTER_ENGFW_PRN_FINISH_PACKAGE_NULL       (PRINTER_SC_ERROR_BASE + 61)

#define PRINTER_ENGFW_SET_PRN_WRONG_PAPERSIZE       (PRINTER_SC_ERROR_BASE + 62)
#define PRINTER_ENGFW_SET_PRN_DUPLEX_BACK_OPEN      (PRINTER_SC_ERROR_BASE + 63)
#define PRINTER_ENGFW_SET_PRN_THICK_BACK_CLOSE      (PRINTER_SC_ERROR_BASE + 64)

#define PRINTER_ENGFW_SET_ENG_IT_MODE_NOT_AVAILABLE (PRINTER_SC_ERROR_BASE + 70)

/*
#define PRINTER_MOTOR_ERROR_BASE              (PRINTER_ERROR_BASE + 20)
#define PRINTER_MOTOR_CONFLICT                (PRINTER_MOTOR_ERROR_BASE + 1)   // request motor on, but motor on dec process
#define PRINTER_MOTOR_DRIVER_INIT_FAIL        (PRINTER_MOTOR_ERROR_BASE + 2) 
#define PRINTER_MOTOR_REG_SPACE_FULL          (PRINTER_MOTOR_ERROR_BASE + 3)
#define PRINTER_MOTOR_REG_WRONG_PARAMETER     (PRINTER_MOTOR_ERROR_BASE + 4)
#define PRINTER_MOTOR_SET_DIR_FAIL            (PRINTER_MOTOR_ERROR_BASE + 5)
#define PRINTER_MOTOR_CHANGE_STEP_TYPE_FAIL   (PRINTER_MOTOR_ERROR_BASE + 6)
#define PRINTER_MOTOR_TIMER_RESET_FAIL        (PRINTER_MOTOR_ERROR_BASE + 7)
#define PRINTER_MOTOR_TIMER_NEW_FAIL          (PRINTER_MOTOR_ERROR_BASE + 8)
#define PRINTER_MOTOR_POLYGON_OFF_FAIL        (PRINTER_MOTOR_ERROR_BASE + 9)
#define PRINTER_MOTOR_NOT_FOUND               (PRINTER_MOTOR_ERROR_BASE + 10)
#define PRINTER_MOTOR_SET_ILLEGAL_MOTOR       (PRINTER_MOTOR_ERROR_BASE + 11)
#define PRINTER_MOTOR_TIMER_CHANGE_FAIL       (PRINTER_MOTOR_ERROR_BASE + 12)
#define PRINTER_MOTOR_SET_WRONG_VALUE         (PRINTER_MOTOR_ERROR_BASE + 13)
#define PRINTER_MOTOR_POLYGON_ON_FAIL         (PRINTER_MOTOR_ERROR_BASE + 14)


#define PRINTER_TIMER_ERROR_BASE             (PRINTER_ERROR_BASE + 50)
#define PRINTER_TIMER_ARRAY_FULL             (PRINTER_TIMER_ERROR_BASE + 1)
#define PRINTER_TIMER_PARAMETER_WRONG        (PRINTER_TIMER_ERROR_BASE + 2)

#define PRINTER_SENSOR_ERROR_BASE            (PRINTER_ERROR_BASE + 100)
#define PRINTER_SENSOR_ARRAY_FULL            (PRINTER_SENSOR_ERROR_BASE + 1)
#define PRINTER_SENSOR_WRONG_SENSOR          (PRINTER_SENSOR_ERROR_BASE + 2)
#define PRINTER_SENSOR_MAPPING_FAIL          (PRINTER_SENSOR_ERROR_BASE + 3)
#define PRINTER_SENSOR_REG_COUNT_MAX         (PRINTER_SENSOR_ERROR_BASE + 4)
#define PRINTER_SENSOR_WRONG_TYPE            (PRINTER_SENSOR_ERROR_BASE + 5)

#define PRINTER_LPH_ERROR_BASE               (PRINTER_ERROR_BASE + 200)
#define PRINTER_LPH_COMP_FAIL                (PRINTER_LPH_ERROR_BASE + 1)


#define PRINTER_FUSER_ERROR_BASE        (PRINTER_ERROR_BASE + 300)
#define PRINTER_FUSER_CALI_FAIL         (PRINTER_FUSER_ERROR_BASE + 1)
#define PRINTER_FUSER_PARAMETER_ERROR   (PRINTER_FUSER_ERROR_BASE + 2)

#define PRINTER_PP_ERROR_BASE                (PRINTER_ERROR_BASE + 500)
#define PRINTER_PP_PARAMETER_ERROR           (PRINTER_PP_ERROR_BASE + 1)
#define PRINTER_PP_WRONG_FLOW                (PRINTER_PP_ERROR_BASE + 2)
#define PRINTER_PP_NULL_POINTER              (PRINTER_PP_ERROR_BASE + 3)
#define PRINTER_PP_ENV_CHANGE_ERROR          (PRINTER_PP_ERROR_BASE + 4)
#define PRINTER_PP_SHIFT_MOTOR_STATE_ERROR   (PRINTER_PP_ERROR_BASE + 5)
#define PRINTER_PP_SHIFT_MOTOR_TIME_OUT      (PRINTER_PP_ERROR_BASE + 6)

#define PRINTER_SC_ERROR_BASE           (PRINTER_ERROR_BASE + 600)
#define PRINTER_SC_PARAMETER_ERROR      (PRINTER_SC_ERROR_BASE + 1)
#define PRINTER_SC_WRONG_FLOW           (PRINTER_SC_ERROR_BASE + 2)
#define PRINTER_SC_NULL_POINTER         (PRINTER_SC_ERROR_BASE + 3)
*/

//Flash error code
#define FLASH_ERROR_BASE	5000
#define FLASH_SUCCESS					API_SUCCESS					
#define FLASH_ADDRESS_INVALID			(FLASH_ERROR_BASE)
#define FLASH_BANK_ERASE_FAILED			(FLASH_ERROR_BASE+1)
#define FLASH_BLOCK_ERASE_FAILED		(FLASH_ERROR_BASE+2)
#define FLASH_BLOCK_NR_INVALID			(FLASH_ERROR_BASE+3)
#define FLASH_BLOCK_PROTECTED			(FLASH_ERROR_BASE+4)
#define FLASH_BLOCK_PROTECT_FAILED		(FLASH_ERROR_BASE+5)
#define FLASH_BLOCK_PROTECTION_UNCLEAR	(FLASH_ERROR_BASE+6)
#define FLASH_BLOCK_UNPROTECTED			(FLASH_ERROR_BASE+7)
#define FLASH_BLOCK_UNPROTECT_FAILED	(FLASH_ERROR_BASE+8)
#define FLASH_CFI_FAILED				(FLASH_ERROR_BASE+9)
#define FLASH_CHIP_ERASE_FAILED			(FLASH_ERROR_BASE+10)
#define FLASH_CHIP_UNPROTECT_FAILED		(FLASH_ERROR_BASE+11)
#define FLASH_FUNCTION_NOT_SUPPORTED	(FLASH_ERROR_BASE+12)
#define FLASH_GROUP_PROTECT_FAILED		(FLASH_ERROR_BASE+13)
#define FLASH_NO_INFORMATION_AVAILABLE	(FLASH_ERROR_BASE+14)
#define FLASH_NO_OPERATIONTO_SUSPEND	(FLASH_ERROR_BASE+15)
#define FLASH_OPERATION_ON_GOING		(FLASH_ERROR_BASE+16)
#define FLASH_OPERATION_TIMEOUT			(FLASH_ERROR_BASE+17)
#define FLASH_PROGRAM_FAILED			(FLASH_ERROR_BASE+18)
#define FLASH_RESPONSE_UNCLEAR			(FLASH_ERROR_BASE+19)
#define FLASH_SPEC_TOO_MANY_BLOCKS		(FLASH_ERROR_BASE+20)
#define FLASH_SPEC_MPU_TOO_SLOW			(FLASH_ERROR_BASE+21)
#define FLASH_SPEC_TOGGLE_FAILED		(FLASH_ERROR_BASE+22)
#define FLASH_VPP_INVALID				(FLASH_ERROR_BASE+23)
#define FLASH_WRONG_TYPE				(FLASH_ERROR_BASE+24)
#define FLASH_PROTECTED					(FLASH_ERROR_BASE+25)
#define CFM_DRV_ERROR_BAD_MEDIA			(FLASH_ERROR_BASE + 26)
#define CFM_DRV_ERROR_FIFO_ERROR		(FLASH_ERROR_BASE + 27)
#define CFM_DRV_ERROR_MEDIA_REMOVED		(FLASH_ERROR_BASE + 28)
#define CFM_DRV_ERROR_PARAM_ERROR		(FLASH_ERROR_BASE + 29)
#define CFM_DRV_ERROR_READ_ERROR		(FLASH_ERROR_BASE + 30)
#define CFM_DRV_ERROR_CMD_ERROR			(FLASH_ERROR_BASE + 31)
#define CFM_DRV_ERROR_MBR_BAD			(FLASH_ERROR_BASE + 32)
#define CFM_DRV_NEED_PARTITION			(FLASH_ERROR_BASE + 33)
#define FLASH_ERROR_SECTION_END			(FLASH_ERROR_BASE + 34)

//Fax error code
#define FAX_ERROR_BASE	5500
#define FAX_SUCCESS						API_SUCCESS					
#define FAX_RX_END						(FAX_ERROR_BASE+0)
#define FAX_TX_NO_NEXT_PAGE				(FAX_ERROR_BASE+1)
#define FAX_TX_END						(FAX_ERROR_BASE+2)
#define FAX_SCHEDULER_BAD_JOB			(FAX_ERROR_BASE+3)
#define FAX_FAIL_TO_SAVE_RX_DATA		(FAX_ERROR_BASE+4)
#define FAX_FAIL_TO_OPEN_PAGE			(FAX_ERROR_BASE+5)
#define FAX_FAIL_TO_DECODE				(FAX_ERROR_BASE+6)
#define FAX_FAIL_TO_MATCH				(FAX_ERROR_BASE+7)
#define FAX_NO_FIND_IN_JOURNAL			(FAX_ERROR_BASE+8)
#define FAX_REDO_SAME_POS				(FAX_ERROR_BASE+9)
#define FAX_ADD_WRONG_DATA				(FAX_ERROR_BASE+10)
#define FAX_PROCESS_TOO_MUCH_DATA		(FAX_ERROR_BASE+11)
#define FAX_ONE_TOUCH_ITEM				(FAX_ERROR_BASE+12)
#define FAX_GROUP_ITEM					(FAX_ERROR_BASE+13)
#define FAX_PHBK_EOP  					(FAX_ERROR_BASE+14)
#define FAX_PHBK_GOOD 					0
#define FAX_PHBK_BAD  					(FAX_ERROR_BASE+15)
#define FAX_CANCEL_JOB 					(FAX_ERROR_BASE+16)
#define FAX_NO_RECORD 					(FAX_ERROR_BASE+17)
#define FAX_RING_IN 					(FAX_ERROR_BASE+18)
#define FAX_FAX_IN 						(FAX_ERROR_BASE+19)
#define FAX_PAPER_TOO_SMALL				(FAX_ERROR_BASE+20)
#define FAX_STORAGE_FULL				(FAX_ERROR_BASE+21)
#define FAX_PRINT_NO_PAGE				(FAX_ERROR_BASE+22)
#define FAX_PRINT_GET_RESOURCE_FAIL		(FAX_ERROR_BASE+23)

#define FAX_BOARD_BASE	5632
//5632(1600h) -> 5887 error code for FaxBoard

//01	ring detect without successful handshake
#define	FAX_RING_DETECT_FAIL			(FAX_BOARD_BASE+0x01)
//02	call aborted, from STOP or <CAN>
#define	FAX_ABORT						(FAX_BOARD_BASE+0x02)
//11	no answer (t1 timeout)
#define	FAX_NO_ANSWER					(FAX_BOARD_BASE+0x11)
//12	received JM without ability v.34 (manufacturer specific)
#define	FAX_NO_ABILITY					(FAX_BOARD_BASE+0x12)
//21	remote cannot receive or send
#define	FAX_REMOTE_TX_RX_FAIL			(FAX_BOARD_BASE+0x21)
//22	comrec error in transmit phase B
#define	FAX_COMREC_TX_ERROR				(FAX_BOARD_BASE+0x22)
//23	comrec invalid command received
#define	FAX_COMREC_ERROR_CMD			(FAX_BOARD_BASE+0x23)
//24	respec error
#define	FAX_RESPEC_ERROR1				(FAX_BOARD_BASE+0x24)
//25	DCS sent three times without response
#define	FAX_FAIL_SEND_DCS				(FAX_BOARD_BASE+0x25)
//26	DIS/DTC received 3 times; DCS not recognized
#define	FAX_FAIL_READ_DCS				(FAX_BOARD_BASE+0x26)
//27	failure to train at 2400 bps or +FMS value
#define	FAX_FAIL_TRAIN					(FAX_BOARD_BASE+0x27)
//28	respec invalid response received
#define	FAX_RESPEC_ERROR_GET			(FAX_BOARD_BASE+0x28)
//29	remote SUB not set
#define	FAX_NO_GET_SUB					(FAX_BOARD_BASE+0x29)
//2A	remote SID not set
#define	FAX_NO_GET_SID					(FAX_BOARD_BASE+0x2A)
//2B	remote PWD not set
#define	FAX_NO_GET_PWD					(FAX_BOARD_BASE+0x2B)
//2C	remote SEP not set
#define	FAX_NO_GET_SEP					(FAX_BOARD_BASE+0x2C)
//51	respec error
#define	FAX_RESPEC_ERROR				(FAX_BOARD_BASE+0x51)
//52	no response to MPS repeated 3 times
#define	FAX_NO_MPS						(FAX_BOARD_BASE+0x52)
//53	invalid response to MPS
#define	FAX_WRONG_MPS_RES				(FAX_BOARD_BASE+0x53)
//54	no response to EOP repeated 3 times
#define	FAX_NO_EOP_RES					(FAX_BOARD_BASE+0x54)
//55	invalid response to EOP
#define	FAX_WRONG_EOP_RES				(FAX_BOARD_BASE+0x55)
//59	no response to PPSMPS repeated 3 times
#define	FAX_NO_PPS_MPS_RES				(FAX_BOARD_BASE+0x59)
//5A	invalid response to PPSMPS
#define	FAX_WRONG_PPS_MPS_RES			(FAX_BOARD_BASE+0x5A)
//5B	no response to PPSEOP repeated 3 times
#define	FAX_NO_PPS_EOP_RES				(FAX_BOARD_BASE+0x5B)
//5C	invalid response to PPSEOP
#define	FAX_WRONG_PPS_EOP_RES			(FAX_BOARD_BASE+0x5C)
//5F	no response to PPSNULL repeated 3 times
#define	FAX_NO_PPS_NULL_RES				(FAX_BOARD_BASE+0x5F)
//60	invalid response to PPSNULL
#define	FAX_WRONG_PPS_NULL_RES			(FAX_BOARD_BASE+0x60)

//61	no response to CTC repeated 3 times
#define	FAX_NO_CTC_RES					(FAX_BOARD_BASE+0x61)
//62	invalid response to CTC
#define	FAX_WRONG_CTC_RES				(FAX_BOARD_BASE+0x61)

//63	no response to EOR repeated 3 times
#define	FAX_NO_EOR_RES					(FAX_BOARD_BASE+0x63)
//64	invalid response to EOR
#define	FAX_WRONG_EOR_RES				(FAX_BOARD_BASE+0x64)
//65	no response to RR repeated 3 times
#define	FAX_NO_RR_RES					(FAX_BOARD_BASE+0x65)
//66	invalid response to RR
#define	FAX_WRONG_RR_RES				(FAX_BOARD_BASE+0x66)
//67	RTN failure at 2400 bps
#define	FAX_RTN_FAIL					(FAX_BOARD_BASE+0x67)
//68	t5 timeout for ECM (manufacturer specific)
#define	FAX_T5_TIMEOUT					(FAX_BOARD_BASE+0x68)
//69	ERR received after EORNULL
#define	FAX_EORNULL_ERR					(FAX_BOARD_BASE+0x69)
//71	respec error
//72	comrec error
//73	t2 timeout, expected page not received
//74	t1 timeout after EOM received
//91	missing EOL after 13 seconds for necm 
//a0-bf : receive phase D hangup codes
//A1	respec invalid response received
//A2	comrec invalid response received
//A4	NULL EOR received, ERR send after DCN received
//e0-ff : reserved for manufacturer specific use
//E0	modem hang-up
//E1	V34 abort received
//E2	V34 t1 timeout, control channel error
//E3	V34 t1 timeout, primary channel error
//E4	line not connected; cannot proceed
//E5	digital line; cannot proceed
//E6	LSD fault during offhook
//E7	data not sent until guard timer expire
//F1	Line not connected, also means dial fail
#define FAX_LINE_NOT_CONNECTED			(FAX_BOARD_BASE+0xE4)
//F2	NO DIALTONE detection
#define FAX_NO_DIALTONE					(FAX_BOARD_BASE+0xF2)
//F3	LINE BUSY
#define FAX_LINE_BUSY					(FAX_BOARD_BASE+0xF3)
//F4	NO CARRIER
//F5	RING
#define	FAX_RING						(FAX_BOARD_BASE+0xF5)
#define FAX_COMMUNICATE_TIMEOUT			(FAX_BOARD_BASE+0xF6)
#define FAX_COMMUNICATE_ERROR			(FAX_BOARD_BASE+0xF7)
//F8	received image fail	
#define	FAX_RX_IMAGE_FAIL				(FAX_BOARD_BASE+0xF8)
//F9	Fax Board error
#define FAX_BOARD_ERROR                 (FAX_BOARD_BASE+0xF9)

 

//================================================= For ScanDocUCO Start
#define SC_DOC_BASE             6000
#define SC_DOC_NOT_INITIAL		(SC_DOC_BASE+1)
#define SC_DOC_READY			   (SC_DOC_BASE+2)
#define SC_DOC_SCANNING			(SC_DOC_BASE+3)
#define SC_DOC_WRONG_STATE		(SC_DOC_BASE+4)
#define SC_DOC_ABORT			   (SC_DOC_BASE+5)
#define SC_DOC_ERROR			   (SC_DOC_BASE+6)

//================================================= For ScanDocUCO End

//================================================= For O_JBIG
#define JBIG_ERROR_BASE         7000
#define JBIG_WRONG_SIZE			JBIG_ERROR_BASE+1
#define JBIG_ENCODE_FAIL        JBIG_ERROR_BASE+2 
#define JBIG_DECODE_MISMATCH  	JBIG_ERROR_BASE+3 
//================================================= O_JBIG End

//================================================= 8000 For IP

// 8000 -> 8999 IP end

//================================================= For PANEL_IO Start

#define PANEL_IO_ERROR_BASE					9000
#define PANEL_IO_SEMAPHORE_DELETE			PANEL_IO_ERROR_BASE+1
#define PANEL_IO_SEMAPHORE_NO_INSTANCE 		PANEL_IO_ERROR_BASE+2
#define PANEL_IO_SEMAPHORE_WAIT_ABORTED		PANEL_IO_ERROR_BASE+3
#define PANEL_IO_SEMAPHORE_ERROR			PANEL_IO_ERROR_BASE+4
#define PANEL_IO_SEMAPHORE_WAIT_ERROR		PANEL_IO_ERROR_BASE+5
 
//================================================= For PANEL_IO End

//================================================= For System Manager Start
#define JOBMGR_ERROR_BASE		10000
#define JOBMGR_BUSY				(JOBMGR_ERROR_BASE)
#define JOBMGR_JOB_CONFLICT		(JOBMGR_ERROR_BASE + 1)
#define JOBMGR_JOB_FULL			(JOBMGR_ERROR_BASE + 2)
#define JOBMGR_PAUSE			(JOBMGR_ERROR_BASE + 3)
#define JOBMGR_NO_APP_RUNNING	(JOBMGR_ERROR_BASE + 4)
#define JOBMGR_ADD_JOB          (JOBMGR_ERROR_BASE + 5)
#define JOBMGR_DEL_JOB          (JOBMGR_ERROR_BASE + 6)
#define JOBMGR_ADD_TASK         (JOBMGR_ERROR_BASE + 7)
#define JOBMGR_DEL_TASK         (JOBMGR_ERROR_BASE + 8)
#define JOBMGR_JOB_NOT_EXIST    (JOBMGR_ERROR_BASE + 10)
#define JOBMGR_ABORT_JOB		(JOBMGR_ERROR_BASE + 11)
#define JOBMGR_ABORT_TASK		(JOBMGR_ERROR_BASE + 12)

#define SYSTEM_ERROR_BASE		10100
#define SYSTEM_BUSY				(SYSTEM_ERROR_BASE)
#define SYSTEM_WARMUP			(SYSTEM_ERROR_BASE+1)
#define SYSTEM_SLEEP			(SYSTEM_ERROR_BASE+2)
#define SYSTEM_USB_DISCONNECT	(SYSTEM_ERROR_BASE+3)
#define SYSTEM_DEV_ALL_READY	(SYSTEM_ERROR_BASE+4)
#define SYSTEM_SUSPEND			(SYSTEM_ERROR_BASE+5)

//================================================= For System Manager End
//================================================= For water mark 
#define WATER_MARK_ERROR         10500
#define DEMO_PAGE_ERROR           (WATER_MARK_ERROR + 1)
//================================================== water mark end 
//================================================== copy paper mismatch
#define COPY_PAPER_MISMATCH      10600

//================================================= For O_MenuSys
#define MENU_ERROR_BASE               11000
#define MENU_FILE_DOESNT_EXIST        MENU_ERROR_BASE+1
#define MENU_WRONG_NODE_TYPE          MENU_ERROR_BASE+2
#define MENU_WRONG_EXEC_FUNC_ID       MENU_ERROR_BASE+3
#define MENU_WRONG_SAVE_INFO          MENU_ERROR_BASE+4

//================================================= O_MenuSys End

//================================================= For O_JobStorage Start
#define JOB_STORAGE_ERROR_BASE				11100
#define JOB_STORAGE_JOB_EXIST				JOB_STORAGE_ERROR_BASE
#define JOB_STORAGE_JOB_NOT_EXIST			JOB_STORAGE_ERROR_BASE+1
#define JOB_STORAGE_JOB_NOT_OPEN			JOB_STORAGE_ERROR_BASE+2
#define JOB_STORAGE_JOB_PARAMETER_ERROR		JOB_STORAGE_ERROR_BASE+3
#define JOB_STORAGE_PASSWD_WRONG			JOB_STORAGE_ERROR_BASE+4
#define JOB_STORAGE_STORAGE_FULL			JOB_STORAGE_ERROR_BASE+5
#define JOB_STORAGE_RENAME_JOB				JOB_STORAGE_ERROR_BASE+6
#define JOB_STORAGE_JOB_ALREADY_OPEN		JOB_STORAGE_ERROR_BASE+7
#define JOB_STORAGE_APPEND_JOB				JOB_STORAGE_ERROR_BASE+8
#define JOB_STORAGE_RW_FAIL					JOB_STORAGE_ERROR_BASE+10
#define JOB_STORAGE_OPEN_USER_FOLDER_FAIL	JOB_STORAGE_ERROR_BASE+11
#define JOB_STORAGE_RENAME_FAIL				JOB_STORAGE_ERROR_BASE+12
#define JOB_STORAGE_JOB_OPEN_DEL_FAIL		JOB_STORAGE_ERROR_BASE+13
#define JOB_STORAGE_SAME_JOB_ABORT			JOB_STORAGE_ERROR_BASE+14
#define JOB_STORAGE_FOLDER_EXISTED			JOB_STORAGE_ERROR_BASE+15
#define JOB_STORAGE_CREATE_FOLDER_FAIL		JOB_STORAGE_ERROR_BASE+16
#define JOB_STORAGE_FILE_NOT_EXIST			JOB_STORAGE_ERROR_BASE+17
#define JOB_STORAGE_GET_FILE_RES_FAIL		JOB_STORAGE_ERROR_BASE+18
#define JOB_STORAGE_CLOSE_FILE_FAIL			JOB_STORAGE_ERROR_BASE+19
#define JOB_STORAGE_DEL_USER_FOLDER_FAIL	JOB_STORAGE_ERROR_BASE+20
#define JOB_STORAGE_JOB_COUNT_FULL			JOB_STORAGE_ERROR_BASE+21
#define JOB_STORAGE_USER_FOLDER_FULL		JOB_STORAGE_ERROR_BASE+22
#define JOB_STORAGE_FILE_LIMIT_REACH		JOB_STORAGE_ERROR_BASE+23
#define JOB_STORAGE_FOLDER_NOT_EXISTED		JOB_STORAGE_ERROR_BASE+24
#define JOB_STORAGE_NO_MORE_ENTRIES			JOB_STORAGE_ERROR_BASE+25
#define JOB_STORAGE_FILE_EXISTED				JOB_STORAGE_ERROR_BASE+26


//================================================= For O_JobStorage End

//================================================= For O_UsbStorage Start
#define USB_STORAGE_ERROR_BASE				11400
#define USB_STORAGE_NOT_READY				USB_STORAGE_ERROR_BASE
#define USB_STORAGE_INVALID_PATH			( USB_STORAGE_ERROR_BASE + 1 )
#define	USB_STORAGE_GET_FILE_INFO_FAIL		( USB_STORAGE_ERROR_BASE + 2 )

//================================================= For O_UsbStorage End

//================================================= For O_StorageMgr Start
#define O_STORAGE_ERROR_BASE				11500
#define O_STORAGE_FILE_NOT_EXIST			O_STORAGE_ERROR_BASE
#define O_STORAGE_RW_FAIL					( O_STORAGE_ERROR_BASE + 1 )

//================================================= For O_StorageMgr End


//================================================= 13000 For FFS
// 13000 -> 13999 FFS
//================================================= For FFS Start

#define FFS_ERROR_BASE						13000
#define FFS_WRONG_INPUT_PARTITION			FFS_ERROR_BASE+1
#define FFS_NULL_INPUT_PTR					FFS_ERROR_BASE+2

 
//================================================= For FFS End


//================================================= 14000 For Accounting
// 14000 -> 14100 Accounting 
//================================================= For Accounting Start
#define ACC_ERROR_BASE			14000
#define ACC_NO_RECORD			ACC_ERROR_BASE + 1	//	eAccount_NoRecord,
#define ACC_DEL_ADMIN_FAIL		ACC_ERROR_BASE + 2	//	eAccount_DeleteAdminError,
#define ACC_WRONG_PARAM			ACC_ERROR_BASE + 3	//	eAccount_ParamIllegal,
#define ACC_ACCOUNT_EXISTED		ACC_ERROR_BASE + 4	//	eAccount_AccountNameExisted,
#define ACC_ACCOUNT_FULL		ACC_ERROR_BASE + 5	//	eAccount_AccountFull,
#define ACC_STR_LEN_WRONG		ACC_ERROR_BASE + 6	//	eAccount_StrLenOutOfRange,
#define ACC_WRONG_PASSWORD		ACC_ERROR_BASE + 7	//	eAccount_WrongPassword,
#define ACC_WRONG_LIMIT_TYPE	ACC_ERROR_BASE + 8	//	eAccount_WrongLimitType,
#define ACC_LIMIT_OUT_RANGE		ACC_ERROR_BASE + 9	//	eAccount_LimitOutOfRange,
#define ACC_USED_UPPER_LIMIT	ACC_ERROR_BASE + 10	//	eAccount_UsedUpperLimit,	//新增前便已達上限值
#define ACC_INC_USED_OUT_RANGE	ACC_ERROR_BASE + 11	//	eAccount_IncUsedOutOfLimit,	//新增後超出上限值
#define ACC_GET_RECORD_ERROR	ACC_ERROR_BASE + 12	//	eAccount_GetRecordError,
#define ACC_READ_RECORD_ERROR	ACC_ERROR_BASE + 13	//	eAccount_ReadRecordFail,
#define ACC_ALREADY_LOGIN		ACC_ERROR_BASE + 14	//	eAccMgr_AlreadyLogin,
#define ACC_LOGIN_COUNT_FULL	ACC_ERROR_BASE + 15	//	eAccMgr_LoginCountFull,
#define ACC_OPER_NO_RECORD		ACC_ERROR_BASE + 16
#define ACC_OPER_ROLE_FAIL		ACC_ERROR_BASE + 17
#define ACC_OPER_NOT_SAME		ACC_ERROR_BASE + 18
#define ACC_ADMIN_CAN_NOT_MODIFY	ACC_ERROR_BASE + 19
#define ACC_LIMIT_ZERO			ACC_ERROR_BASE + 20
#define ACC_WRITE_RECORD_FAIL	ACC_ERROR_BASE + 21
#define ACC_READ_RECORD_FAIL	ACC_ERROR_BASE + 22
#define ACC_NO_ACCOUNT_NAME		ACC_ERROR_BASE + 23
#define ACC_BCP_PRINT_DISABLE	ACC_ERROR_BASE + 24 //BCP Print Disable
#define ACC_SEND_AUTH_FAIL		ACC_ERROR_BASE + 25 
#define ACC_BP_OUT_OF_QUOTA		ACC_ERROR_BASE + 26 

//================================================= 14100 For Accounting
// 14100 -> 14200 Accounting (X2030) 
//================================================= For Accounting Start
#define ACC_ERROR_X2030_BASE			14100

#define ACC_CP_NVRAM_FAIL		ACC_ERROR_X2030_BASE + 1
#define ACC_NOTIFY_FAIL			ACC_ERROR_X2030_BASE + 2

//================================================= For Accounting End

//============================================================// For Copy App Error
#define APP_ERROR_BASE						15000
#define APP_ERROR_JOB_CANCELLED 			APP_ERROR_BASE
#define APP_ERROR_SCANNER_ERROR 			APP_ERROR_BASE + 1
#define APP_ERROR_IP_ERROR 					APP_ERROR_BASE + 2
#define APP_ERROR_LIMITS_REACHED 			APP_ERROR_BASE + 3
#define APP_ERROR_CSA6_FAILED				APP_ERROR_BASE + 4
#define APP_ERROR_MEMORY_FULL				APP_ERROR_BASE + 5
#define APP_ERROR_STORAGE_RW_FAILED			APP_ERROR_BASE + 6
#define APP_ERROR_MFP_NOT_READY				APP_ERROR_BASE + 7
#define APP_ERROR_UNKNOWN_ERROR				APP_ERROR_BASE + 8
//COPY
#define APP_ERROR_WATERMARK_FAILED			APP_ERROR_BASE + 9
#define APP_ERROR_TRAY_NOT_SUIT				APP_ERROR_BASE + 10
#define APP_ERROR_TRAY_NOT_READY			APP_ERROR_BASE + 11
//REPRINT SAVED JOB
#define APP_ERROR_FILE_DELETE_FAILED		APP_ERROR_BASE + 12
#define APP_ERROR_FILE_NOT_EXISTED			APP_ERROR_BASE + 13
#define APP_ERROR_INVALID_PASSWORD			APP_ERROR_BASE + 14
#define APP_ERROR_PAPER_EMPTY				APP_ERROR_BASE + 15
#define APP_ERROR_NO_MATCH_PAPER			APP_ERROR_BASE + 16
#define APP_ERROR_PAPER_NO_SUPPORT			APP_ERROR_BASE + 17
//WORKFLOW SCANNING
#define APP_ERROR_JOB_NAME_EXISTED			APP_ERROR_BASE + 18
#define APP_ERROR_USB_DISK_NOT_FOUND		APP_ERROR_BASE + 19
#define APP_ERROR_USB_CONNECT_FAILED		APP_ERROR_BASE + 20
#define APP_ERROR_UNABLE_TO_DISPATCH_EMAIL	APP_ERROR_BASE + 21

#define APP_ERROR_PAGE_DATA_NOT_READY		APP_ERROR_BASE + 22
#define APP_ERROR_PAGE_END					APP_ERROR_BASE + 23
// MULTI ID CARD COPY
#define APP_ERROR_MULTI_CARD_DETECTED_ERROR	APP_ERROR_BASE + 24

//================================================= 16000 For Report
// 16000 -> 16100 Report 
//================================================= for Report

#define REPORT_APP_ERROR_BASE              16000
#define REPORT_APP_WRONG_PARAMETER         REPORT_APP_ERROR_BASE + 1 //Report wrong parameter
#define REPORT_APP_SYSTEM_NOT_READY        REPORT_APP_ERROR_BASE + 2 // MFP not ready error 
#define REPORT_APP_MEMORY_EMPTY            REPORT_APP_ERROR_BASE + 3 // memory empty 
#define REPORT_APP_STORAGE_RW_FAIL         REPORT_APP_ERROR_BASE + 4 // storage r/w fail
#define REPORT_APP_STORAGE_FILE_NOT_EXIST  REPORT_APP_ERROR_BASE + 5 // storage file not exist 
#define REPORT_APP_PAPER_EMPTY             REPORT_APP_ERROR_BASE + 6 // paper empty 
#define REPORT_APP_PAPER_NOT_SUPPORT       REPORT_APP_ERROR_BASE + 7 // paper empty 
#define REPORT_APP_UNKNOW_ERROR            REPORT_APP_ERROR_BASE + 8 // unknow error 
#define REPORT_APP_LIMITS_REACHED			REPORT_APP_ERROR_BASE + 9 // unknow error

//================================================= For Report end

//============================================================// For Report Error

//============================================================// For Reprint Saved Job Error
#define REPRINT_SAVED_JOB_ERROR_BASE		16100
#define REPRINT_SAVED_JOB_NO_MATCH_PAPER			REPRINT_SAVED_JOB_ERROR_BASE + 1 // no match paper error
#define REPRINT_SAVED_JOB_PDF_SIZE_OVER_LIMITATION	REPRINT_SAVED_JOB_ERROR_BASE + 2 // Error in printing PDF file over 30MB

//============================================================// For scan to APP job error
//Translate the error code of ScanToNet APP into defined error number in ErrorDef.h. 20160906 block begin
//Define the error number for APP to respond by ScanToApp's error code.
#define SCAN_TO_NET_ERROR_BASE				16200
#define SCAN_ERR_INVALID_LOGIN_PASSWORD		SCAN_TO_NET_ERROR_BASE + 1
#define SCAN_ERR_CONNECTION_FAIL			SCAN_TO_NET_ERROR_BASE + 2
#define SCAN_ERR_UNKNOW_ERROR               SCAN_TO_NET_ERROR_BASE + 3
//end

//extra error code for NTF_CUSTOM_ERROR
#define NET_PRINT_JOB_FLUSH					16300

//error code 5xxxxx are defined for network module error.
#define FUNC_ERR_NETWORK_UPPER_BOUND							500000
#define FUNC_ERR_NETWORK_LOWER_BOUND							599999

//Function error defined in SPEC
//============================================================// 
#define FUNC_ERR_BUFFER_FULL										600011
#define FUNC_ERR_FILE_NAME_EXISTED								600012
#define FUNC_ERR_NO_ENTRY_FOUND									600013
#define FUNC_ERR_MFP_NOT_READY									600014
#define FUNC_ERR_INVALID_LOGIN_INFO								600015
#define FUNC_ERR_UNKNOWN_ERROR									600018
#define FUNC_ERR_EXCEED_MAX_NUM									600100
#define FUNC_ERR_NO_FAX_NUM_ADDED								600101
#define FUNC_ERR_FAX_COMM_ERROR									600102
#define FUNC_ERR_LINE_IN_USE										600103
#define FUNC_ERR_EXCEED_ALLOWABLE_LIMIT							600200
#define FUNC_ERR_NO_RECIPIENT_ADDED								600201
#define FUNC_ERR_NO_FORM_ADDR_ADDED								600202
#define FUNC_ERR_RESET_DEFAULT_FAIL								600300
#define FUNC_ERR_CALIBRATION_FAIL									600301
#define FUNC_ERR_RESET_COUNT_FAIL									600302
#define FUNC_ERR_SET_FAIL											600303
#define FUNC_ERR_PAPER_NOT_SUPPORT								600304
#define FUNC_ERR_IMAGE_TOO_LIGHT									600305
#define FUNC_ERR_USB_DISK_NOT_FOUND								600500
#define FUNC_ERR_USB_DISK_CONNECT_FAIL							600501
#define FUNC_ERR_DEVICE_NO_RESPONSE								600502
#define FUNC_ERR_UNSUPPORTED_DEVICE								600503
#define FUNC_ERR_UNSUPPORTED_HUB									600504
#define FUNC_ERR_UNSUPPORTED_MEDIA_TYPE							600600
#define FUNC_ERR_UNSUPPORTED_PAPER_SIZE							600601

//============================================================//
#define FUNC_ERR_UPPER_BOUND										500000
#define FUNC_ERR_LOWER_BOUND										699999

//============================================================// For IPS error, RANGE : 910000~919999
#define IPS_ERR_BASE											910000
#define IPS_ERR_PDF_CORRUPTED									IPS_ERR_BASE + 0
#define IPS_ERR_PDF_ENCRYPTED									IPS_ERR_BASE + 1
#define IPS_ERR_PDF_NORESOURCE									IPS_ERR_BASE + 2

//============================================================//For Print Data
#define PRN_DATA_CORRUPTED				910100

//============================================================// For Activation and account error, RANGE : 930000~939999
#define ACTIVATION_ERR_BASE				930000
#define OUTOFQOUTA						930001
#define LOWQUOTA						930002
#define DEADLINENEAR					930003
#define SEND_AUTH_FAIL					930004
#define ACTIVATION_ERR_SN				930100
#define ACTIVATION_ERR_DEADLINE			930101
#define ACTIVATION_ERR_QUOTA			930102
#define ACTIVATION_ERR_CODE				930103

//============================================================// For Card reader error code,
//與 Server連不通的 error 透過 XI_SET_ERRORCODE 所註冊的 O_ServerNetErrCode_Set 通知 UI 跟 Neil，且排除時會通知
#define PORT9100_RECEIVE_DATA_TIMEOUT					900210
#define	INFO_URL_ADDR_IS_EMPTY							900221
#define INFO_FAIL_TO_CONNECT_HTTPSERVER					900222
#define	INFO_FAIL_TO_SEND_HTTP_HEADER					900223
#define	INFO_FAIL_TO_SEND_DATA							900224
#define INFO_RECEIVE_DATA_TIMEOUT						900225
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_INFO_PAGE	900226
#define CONFIG_URL_ADDR_IS_EMPTY						900231
#define CONFIG_FAIL_TO_CONNECT_HTTPSERVER				900232
#define CONFIG_FAIL_TO_SEND_HTTP_HEADER					900233
#define	CONFIG_FAIL_TO_SEND_DATA						900234
#define CONFIG_RECEIVE_DATA_TIMEOUT 					900235
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_CONFIG_PAGE	900236
#define CANCEL_URL_ADDR_IS_EMPTY						900241
#define	CANCEL_FAIL_TO_CONNECT_HTTPSERVER				900242
#define	CANCEL_FAIL_TO_SEND_HTTP_HEADER					900243
#define	CANCEL_FAIL_TO_SEND_DATA						900244
#define CANCEL_RECEIVE_DATA_TIMEOUT						900245
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_CANCEL_PAGE	900246
#define	PULL_URL_ADDR_IS_EMPTY							900251
#define PULL_FAIL_TO_CONNECT_HTTPSERVER 				900252
#define PULL_FAIL_TO_SEND_HTTP_HEADER					900253
#define	PULL_FAIL_TO_SEND_DATA							900254
#define PULL_RECEIVE_DATA_TIMEOUT						900255
#define	PULL_THE_SIZE_OF_RECEIVE_DATA_IS_WRONG			900256
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_PULL_PAGE 	900257
#define PRE_PARSE_GARBAGE_DATA							900258	//Pre-Parse Garbage data. 900258 errorhandle.
#define	UPDATE_URL_ADDR_IS_EMPTY						900261
#define UPDATE_FAIL_TO_CONNECT_HTTPSERVER 				900262
#define	UPDATE_FAIL_TO_SEND_HTTP_HEADER					900263
#define	UPDATE_FAIL_TO_SEND_DATA						900264
#define UPDATE_RECEIVE_DATA_TIMEOUT						900265
#define	UPDATE_THE_SIZE_OF_RECEIVE_DATA_IS_WRONG		900266
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_UPDATE_PAGE 900267
#define	DOCUMENTLIST_URL_ADDR_IS_EMPTY					900271
#define DOCUMENTLIST_FAIL_TO_CONNECT_HTTPSERVER 		900272
#define	DOCUMENTLIST_FAIL_TO_SEND_HTTP_HEADER			900273
#define	DOCUMENTLIST_FAIL_TO_SEND_DATA					900274
#define	RECEIVE_DATA_TIMEOUT							900275
#define	DOCUMENTLIST_THE_SIZE_OF_RECEIVE_DATA_IS_WRONG	900276
#define	CONFIRM_URL_ADDR_IS_EMPTY						900281
#define CONFIRM_FAIL_TO_CONNECT_HTTPSERVER				900282
#define	CONFIRM_FAIL_TO_SEND_HTTP_HEADER				900283
#define	CONFIRM_FAIL_TO_SEND_DATA						900284
#define	CONFIRM_RECEIVE_DATA_TIMEOUT					900285
#define	SERVER_REPLY_HTTPSTATUS_CODE_ERR_IN_CONFIRM_PAGE 900286

//server 發過來的error 透過 XI_SET_SERVER_ERR 所註冊的 O_ServerErrInfo_Set 通知 UI 就好，沒有排除時的通知
#define INVALID_IDCARD_ERR_CODE			921001
#define INSUFFICIENT_BALANCE_ERR_CODE	921002
#define DOCUMENT_NOT_FOUND_ERR_CODE		921003
#define DEVICE_BUSY_ERR_CODE			921004
#define PRINTER_ERROR_ERR_CODE			921005
#define PRINTER_JOB_NOTEXIST_ERR_CODE	921006
#define PRINTER_JOB_ISPRINTING_ERR_CODE	921007
#define PRINTER_NOTEXIST_ERR_CODE	    921008
#define SYSTEM_MAINTAIN_ERR_CODE        921999

typedef int AvApiRet ;

#endif
